Update ScoreBoard.hx
Geokureli/Newgrounds pull request #73
Opened 2023-09-25 17:23 UTC by SeiferTim

Add an optional Callback to `postScore` to know when posting is completed successfully. (Otherwise, you might miss this new score when grabbing the hiscores)

2023-09-25 17:30 UTC, SeiferTim commented
If there is a better way to do this, then you can scrap this PR - this is just how I managed to get it to work for me.

2023-09-26 17:36 UTC, Geokureli requested changes
This will only call the callback on success, the API uses outcomes for callbacks so that:

1. The callback is called on failure as well as success
2. The dev knows why it failed, if it does (I.E.: network issue, general server issues, or issues with the specific api call)

Look into the callback for [requestScores](https://github.com/Geokureli/Newgrounds/blob/master/lib/Source/io/newgrounds/objects/ScoreBoard.hx#L44-L66). I've also provided an untested suggestion

2023-09-26 17:36 UTC, Geokureli commented on lib/Source/io/newgrounds/objects/ScoreBoard.hx
> +			_core.calls.scoreBoard.postScore(id, value, tag).send();
```suggestion
	public function postScore(value:Int, tag:String = null, ?callback:(Outcome<CallError>)->Void):Void {
		var call = _core.calls.scoreBoard.postScore(id, value, tag);
		
		if (callback != null)
			call.addOutcomeHandler(callback);
		
		call.send();
```
Note: I didn't test this

2023-09-26 21:35 UTC, SeiferTim reviewed
I tested this code and it works. (I don't understand these reviews lol)

2023-09-26 21:35 UTC, SeiferTim commented on lib/Source/io/newgrounds/objects/ScoreBoard.hx
> +			_core.calls.scoreBoard.postScore(id, value, tag).send();
```suggestion
	public function postScore(value:Int, tag:String = null, ?callback:Null<(CallOutcome<PostScoreData>) -> Void>):Void {
		final call = _core.calls.scoreBoard.postScore(id, value, tag);
		if (callback != null)
			call.addOutcomeHandler(callback);
		call.send();
	}
```
This works.

2023-09-26 21:48 UTC, Geokureli approved these changes

2023-09-26 21:49 UTC, Geokureli commented
I see what I did wrong, sorry 1 sec

2023-09-26 22:11 UTC, Geokureli commented on lib/Source/io/newgrounds/objects/ScoreBoard.hx
> +				(o)->switch (o) {
FYI `(o)->switch (o) {` is just shorthand for

```hx
function (outcome:CallOutcome<PostScoreData>) {
	
	switch (o) {
		//...
	}
}
```

2023-09-26 22:13 UTC, Geokureli commented
I tested this, it compiles, but I need to use it in a test project, while I do that would you be able to test your current use case against this?

2023-09-27 16:11 UTC, merged

2023-09-27 16:11 UTC, Geokureli commented
thanks!